---
# Create key file with <device>_key and encrypt devices

- name: Create key root file
  copy:
      dest: "/etc/root_key"
      content: |
        {{ item.rootpassphrase }}
  with_items: "{{ gluster_infra_tangserver_config }}"
  when: gluster_infra_tangserver_config is defined

- name: Bind tang server with clevis
  shell: echo ‘YES’ | clevis luks bind -f -k /etc/root_key -d  {{ item.rootdevice }} tang ' {"url":"{{item.url}}"} '
  with_items: "{{ gluster_infra_tangserver_config }}"
  when: gluster_infra_tangserver_config is defined

- name: Add network entry on /etc/dracut.conf.d/clevis.conf
  blockinfile:
    path: /etc/dracut.conf.d/clevis.conf
    state: present
    block: |
      kernel_cmdline="ip=eno1:dhcp"
      omit_dracutmodules+="{{ item.networkinterface }}"
    marker: "# {mark} Entry for {{item.networkinterface}}"
  with_items: "{{ gluster_infra_tangserver_config }}"
  when: gluster_infra_tangserver_config is defined

- name: Execute dracut -vf to configure tang
  shell: dracut -vf
  when: gluster_infra_tangserver_config is defined
