---
# Create key file with <device>_key and encrypt devices

- name: Create key root file
  no_log: true
  copy:
      dest: "/etc/root_key"
      content: |
        {{ rootpassphrase }}
  when: gluster_infra_tangservers is defined

- name: Bind tang server with clevis
  no_log: true
  shell: echo ‘YES’ | clevis luks bind -f -k /etc/root_key -d  {{ rootdevice }} tang ' {"url":"{{item.url}}"} '
  with_items: "{{ gluster_infra_tangservers }}"
  when: gluster_infra_tangservers is defined

- name: Add network entry on /etc/dracut.conf.d/clevis.conf
  no_log: true
  blockinfile:
    path: /etc/dracut.conf.d/clevis.conf
    state: present
    block: |
      kernel_cmdline="ip=eno1:dhcp"
      omit_dracutmodules+="{{ networkinterface }}"
    marker: "# {mark} Entry for {{networkinterface}}"
  with_items: "{{ gluster_infra_tangservers }}"
  when: gluster_infra_tangservers is defined

- name: Execute dracut -vf to configure tang
  no_log: true
  shell: dracut -vf
  when: gluster_infra_tangservers is defined
