---
# This play is for blacklist devices
- name: Flush all empty multipath devices
  shell: multipath -F

- name: Create /etc/multipath/conf.d if doesn't exists
  file:
    path: /etc/multipath/conf.d
    recurse: yes
    state: directory

- name: "Blacklist gluster multipath devices"
  no_log: true
  blockinfile:
    path: /etc/multipath/conf.d/blacklist.conf
    create: yes
    state: present
    block: |
      blacklist {
         devnode "^{{ item }}"
      }
    marker: "# {mark} {{ item }} will be blacklisted"
  with_items: "{{ blacklist_mpath_devices }}"
  when: blacklist_mpath_devices | length > 0

- name: Reload multipathd
  shell: systemctl reload multipathd
