---
# This play is for blacklist devices
- name: Ensure that multipathd services is running
  service:
    name: multipathd
    state: started
    enabled: yes

- name: Flush all empty multipath devices
  shell: multipath -F

- name: Create /etc/multipath/conf.d if doesn't exists
  file:
    path: /etc/multipath/conf.d
    recurse: yes
    state: directory

- name: Get the UUID of the devices
  shell: multipath -a /dev/{{ item }}
  register: dev_uuid
  with_items: "{{ blacklist_mpath_devices }}"

- name: "Blacklist gluster multipath devices"
  blockinfile:
    path: /etc/multipath/conf.d/blacklist.conf
    create: yes
    state: present
    block: |
      blacklist {
         wwid "{{ item.stdout.split()[1][1:-1] }}"
      }
    marker: "# {mark} device {{ item.stdout.split()[1][1:-1] }} will be blacklisted"
  loop: "{{ dev_uuid.results }}"
  when: blacklist_mpath_devices | length > 0

- name: Reload multipathd
  shell: systemctl reload multipathd
