---
# This play is for create key file with <device>_key and encrypt devices

- name: Create key file
  no_log: true
  copy:
      dest: "/etc/{{ item.devicename.split('/')[-1] }}_key"
      content: |
        {{ item.passphrase }}
  with_items: "{{ gluster_infra_luks_devices }}"
  when: gluster_infra_luks_devices is defined

- name: Encrypt devices using key file
  no_log: true
  shell: echo ‘YES’ | cryptsetup luksFormat {{ item.devicename }} /etc/{{ item.devicename.split('/')[-1] }}_key
  with_items: "{{ gluster_infra_luks_devices }}"
  when: gluster_infra_luks_devices is defined

- name: Open encrypt devices using key file
  no_log: true
  shell: cryptsetup luksOpen {{ item.devicename }} luks_{{ item.devicename.split('/')[-1] }} -d /etc/{{ item.devicename.split('/')[-1] }}_key
  with_items: "{{ gluster_infra_luks_devices }}"
  when: gluster_infra_luks_devices is defined

- name: Find UUID for encrypted devices
  no_log: true
  shell: cryptsetup luksUUID {{ item.devicename }}
  register: device_uuid
  with_items: "{{ gluster_infra_luks_devices }}"
  when: gluster_infra_luks_devices is defined

- name: Add encrypted device entry on /etc/crypttab to auto unlock
  no_log: true
  blockinfile:
    path: "/etc/crypttab"
    state: present
    block: |
      luks_{{ item.devicename.split('/')[-1] }} UUID={{ dev_uuid.results[index].stdout }} /etc/{{ item.devicename.split('/')[-1] }}_key
    marker: "# {mark} Entry for {{item.devicename}}"
  loop: "{{ gluster_infra_luks_devices }}"
  loop_control:
    index_var: index
  when: gluster_infra_luks_devices is defined
